set dotenv-load := false

default:
  @just --list

validate:
  scripts/validate-features.sh
  @for script in src/*/install.sh; do sh -n "$script"; done
  @for script in test/*/*.sh test/_global/*.sh; do bash -n "$script"; done
  scripts/validate-skills.sh

check: validate
  @for feature in src/*; do \
    version=$$(jq -r .version "$$feature/devcontainer-feature.json"); \
    grep -F "## [$$version]" "$$feature/CHANGELOG.md" >/dev/null || { echo "Missing changelog entry for $${feature##*/} $$version" >&2; exit 1; }; \
  done
  scripts/check-feature-table.sh

test feature base_image="mcr.microsoft.com/devcontainers/base:ubuntu":
  npm exec -- devcontainer features test --skip-scenarios -f "{{feature}}" -i "{{base_image}}" .

test-scenarios feature:
  npm exec -- devcontainer features test -f "{{feature}}" --skip-autogenerated --skip-duplicated .

test-global:
  npm exec -- devcontainer features test --global-scenarios-only .

test-all: check
  npm exec -- devcontainer features test .
